version: '3.8'
services:
    php:
        container_name: ${COMPOSE_PROJECT_NAME}-php
        build:
            args:
                user: mchernov
                uid: 1000
            context: ./
            dockerfile: ./.docker/php/Dockerfile
        volumes:
            - ./src:/var/www/
            - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini

    nginx:
        image: nginx:latest
        container_name: ${COMPOSE_PROJECT_NAME}-nginx
        volumes:
            - ./src:/var/www
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8081:80"
            - "443:443"
        links:
            - php

    postgres:
        image: postgres:latest
        container_name: ${COMPOSE_PROJECT_NAME}-postgres
        volumes:
            - ./postgres:/data/postgres
            - ./docker/postgresql/data:/var/lib/postgresql/data
        ports:
            - ${POSTGRES_PORT:-5432}:5432
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        restart: always # always restart unless stopped manually

    pgadmin:
        container_name: ${COMPOSE_PROJECT_NAME}-pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        depends_on:
            - postgres
        ports:
            - "${PGADMIN_PORT:-5050}:80"
        restart: unless-stopped
